### ISSUE TITLE
Missing dependency, including prebuilt samples? (dxcompiler.dll)

### ISSUE THREAD

**Issue by lucasfisher0** [RavEngine/Samples#4]
Attempting to run the compiled .EXE from either a source build or [RavEngine_Samples_Winx64 from this run](https://github.com/RavEngine/Samples/actions/runs/5778718890) results in a 'missing dxcompiler.dll' error. This is for WIN64.

I was able to download the dxcompiler.dll manually so it's not too big an issue, but seeing as this exists on the prebuilt samples, I figured I'd report it.
https://github.com/microsoft/DirectXShaderCompiler/releases

**Comment by Ravbug** [comment]
Hi, thanks for the report.

The dependency on dxcompiler.dll should be removed in the latest commits.
