### ISSUE TITLE
RX 6950 XT graphical glitches

### ISSUE THREAD

**Issue by zazahunter** [RavEngine/Samples#5]
![image](https://github.com/RavEngine/Samples/assets/140970127/324b4cc7-c1d8-4439-bf0a-e6b42716237c)
On RX 6950 XT i am facing this issue i tried it on rtx 2070 super and on integrated graphics from both amd and intel and none of them are having this issue.

it kinda seems like a driver bug but i am not skilled enough to know.

**Comment by zazahunter** [comment]
https://youtu.be/zqQRq69cEx0
here is a video showing a few of the problems i get

**Comment by Ravbug** [comment]
Hi, thanks for the report!

This is a known issue with certain GPUs. We're working on a fix but can't give an ETA.

**Comment by zazahunter** [comment]
![image](https://github.com/RavEngine/Samples/assets/140970127/51d2e1e0-9082-4daa-aa6a-e8d842a598aa)
it seems to be fixed? that was quick (i took the latest version of ravengine and i dont see any issues)

**Comment by Ravbug** [comment]
I've been working on a fix for it. It might be resolved on your GPU but it's definitely not fixed for all GPUs (Radeon 5500M still exhibits artifacts for instance)

**Comment by zazahunter** [comment]
hey,

i tested on a windows laptop that also has the rx 5500m and i dont see any issues there.
on my end i test all of the modes in airhockey and all of them work fine on both the rx 5500m and the rx 6950 xt

**Comment by zazahunter** [comment]
i think i will close this issue because so far it seems that all of the issues are fixed i will create a new issue when i have any issues again
